---
- name: Install WEB & PHP
  apt: name={{item}} state=present
  with_items:
      - "{{web_packages}}"

- name: Change Default Configuration Nginx
  template: src=files/nginx/default.tpl dest=/etc/nginx/sites-available/default
  notify: Restart Nginx
