---
- hosts: all
  sudo: yes
  vars:
    doc_root: '/vagrant/web'
    server_name: "{{ ansible_eth1.ipv4.address }}"
    sys_packages: ['curl','vim','git']
    web_packages: ['nginx','php5-fpm','php5-cli','php5-curl']

  tasks:
  - include_tasks: tasks/init.yml
  - include_tasks: tasks/web.yml      
  - shell: echo "{{ ansible_eth1.ipv4.address }}"
    register: result
  - debug: msg="Address is {{ result.stdout }}"

  handlers:
  - name: Restart Nginx
    action: service name=nginx state=restarted

  - name: Restart PHP5-FPM
    action: service name=nginx state=restarted

